apisix:
  node_listen:
    - port: 9080

plugin_attr:
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091

deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml

# END
